---
output: github_document
---

```{r}
library(dplyr)
library(knitr)
library(tidyr)
```

## Benchmark files produced by snakemake

```{r}
bm.df = lapply(list.files('benchmark'), function(fpath){
  df = read.table(paste0('benchmark/', fpath), as.is=TRUE, sep='\t', header=TRUE)
  df$task = gsub('.benchmark.tsv', '', fpath)
  df
}) %>% bind_rows

bm.df = bm.df %>%
  mutate(sample=gsub("[^\\.]+\\.(.+)", "\\1", task),
         task=gsub("([^\\.])\\..+", "\\1", task)) %>%
  select(task, sample, everything())
```

### Average resources per task

```{r}
bm.df %>% group_by(task) %>% summarize(cpu_h=mean(cpu_time/3600),
                                       min=mean(s/60),
                                       mean_load=mean(mean_load),
                                       max_rss=mean(max_rss)) %>%
  kable(format.args=list(big.mark=','))
```

## Average per input type for the `vg annotate` task

```{r}
bm.df %>% filter(task=='vg_annotate') %>% mutate(input=gsub('(.+)_.+', '\\1', sample)) %>%
  group_by(input) %>% summarize(cpu_h=mean(cpu_time/3600),
                                min=mean(s/60),
                                mean_load=mean(mean_load),
                                max_rss=mean(max_rss)) %>%
  kable(format.args=list(big.mark=','))
```

